class _NonRetryableError(Exception):
    pass
